// Generated by CoffeeScript 1.7.1
'use strict';
app.controller('MainCtrl', function($scope, $rootScope, $http) {});

app.controller('NavbarCtrl', function($scope, $rootScope, $location, Auth) {
  $scope.logout = function() {
    return Auth.logout().then(function() {
      return $location.path('/login');
    });
  };
});

app.controller('CrumbCtrl', function($scope, $rootScope, $location) {
  $scope.crumb = function(url) {
    var config, menu, submenu, _i, _j, _len, _len1, _ref, _ref1;
    config = $rootScope.config;
    if (config === void 0) {
      return "";
    }
    _ref = config.menus;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      menu = _ref[_i];
      if (menu.href === url) {
        return menu.name;
      }
      if (menu.submenus) {
        _ref1 = menu.submenus;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          submenu = _ref1[_j];
          if (submenu.href === url) {
            return "" + menu.name + " -- " + submenu.name;
          }
        }
      }
    }
  };
});

app.controller('SidebarCtrl', function($scope, $rootScope) {
  $scope.menus = $rootScope.config.menu;
});

app.controller('LoginCtrl', function($scope, $rootScope, Auth, $location) {
  if (Auth.isLoggedIn()) {
    $location.path('/');
  }
  $scope.user = {};
  $scope.errors = {};
  $scope.login = function(form) {
    $scope.submitted = true;
    if (form.$valid) {
      return Auth.login({
        email: $scope.user.email,
        password: $scope.user.password
      }).then(function() {
        return $location.path('/');
      })["catch"](function(err) {
        return $scope.errors.other = err.data.message;
      });
    }
  };
});

app.controller('SignupCtrl', function($scope, Auth, $location) {
  if (Auth.isLoggedIn()) {
    $location.path('/');
  }
  $scope.user = {};
  $scope.errors = {};
  $scope.register = function(form) {
    $scope.submitted = true;
    if (form.$valid) {
      return Auth.createUser({
        name: $scope.user.name,
        email: $scope.user.email,
        password: $scope.user.password
      }).then(function() {
        return $location.path('/');
      })["catch"](function(err) {
        return angular.forEach(err.data.errors, function(error, field) {
          form[field].$setValidity('mongoose', false);
          return $scope.errors[field] = error.message;
        });
      });
    }
  };
});
