// Generated by CoffeeScript 1.7.1
'use strict';
var path;

path = require('path');


/*
如果view目录下面包含该html页面则返回该页面，如果不存在则返回404
 */

exports.partials = function(req, res) {
  var requestedView;
  requestedView = path.join('./', req.url.split('.')[0]);
  return res.render(requestedView, function(err, html) {
    if (err) {
      console.log("Error rendering partial'" + requestedView + "' \n" + err);
      res.status(404);
      return res.send(404);
    } else {
      return res.send(html);
    }
  });
};


/*
返回SPA主页
 */

exports.index = function(req, res) {
  return res.render('index');
};
