// Generated by CoffeeScript 1.7.1
'use strict';
var User, mongoose, passport;

mongoose = require('mongoose');

passport = require('passport');

User = mongoose.model('User');


/*
 * 创建用户
 */

exports.create = function(req, res, next) {
  var newUser;
  newUser = new User(req.body);
  newUser.provider = 'local';
  return newUser.save(function(err) {
    if (err) {
      return res.json(400, err);
    }
    return req.logIn(newUser, function(err) {
      if (err) {
        return next(err);
      }
      return res.json(req.user.userInfo);
    });
  });
};


/*
 * 获取用户资料
 * 如果制定用户id，则返回对应id资料，如果未指定返回当前用户资料
 */

exports.show = function(req, res, next) {
  var userId;
  userId = req.params.id;
  if (userId) {
    return User.findById(userId, function(err, user) {
      if (err) {
        return next(err);
      }
      if (!user) {
        return res.send(404);
      }
      return res.send({
        profile: user.profile
      });
    });
  } else {
    return res.send({
      profile: req.user.profile
    } || null);
  }
};


/*
 * 更改密码
 */

exports.changePassword = function(req, res, next) {
  var newPass, oldPass, userId;
  userId = req.user._id;
  oldPass = String(req.body.oldPassword);
  newPass = String(req.body.newPassword);
  return User.findById(userId, function(err, user) {
    if (user.authenticate(oldPass)) {
      user.password = newPass;
      return user.save(function(err) {
        if (err) {
          return res.send(400);
        }
        return res.send(200);
      });
    } else {
      return res.send(403);
    }
  });
};


/*
 * 获取当前用户
 */

exports.me = function(req, res) {
  return res.json(req.user || null);
};


/*
 * 获取配置信息
 */

exports.config = function(req, res) {
  var config;
  config = {
    user: {
      name: 'Eric Wang',
      role: 'admin',
      avatar: '/assets/avatars/user.jpg'
    },
    company: {
      name: '企业移动管理平台',
      logo: '/images/logo.png'
    },
    menus: [
      {
        "name": "首页",
        "icon": "icon-dashboard",
        "href": "/"
      }, {
        "name": "设置",
        "icon": "icon-laptop",
        "href": "/settings"
      }, {
        "name": "用户",
        "icon": "icon-user",
        "href": "#",
        "submenus": [
          {
            "href": "/customers/role",
            "name": "角色管理"
          }, {
            "href": "/customers/user",
            "name": "用户管理"
          }, {
            "href": "/customers/source",
            "name": "资源管理"
          }, {
            "href": "/customers/custom",
            "name": "客户管理"
          }, {
            "href": "/customers/partner",
            "name": "合作商管理"
          }, {
            "href": "/customers/dept",
            "name": "用户组管理"
          }
        ]
      }, {
        "name": "内容",
        "icon": "icon-folder-open-alt",
        "href": "#",
        "submenus": [
          {
            "href": "/push",
            "name": "推送消息",
            "id": "msg_list"
          }
        ]
      }
    ]
  };
  return res.json(config);
};
